# Sindle dimension Numpy Array

In [185]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [186]:
import numpy as np
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [187]:
type(n1)

numpy.ndarray

# Multi Dimensional Numpy Array

In [188]:
import numpy as np
n2=np.array([
    [10,20,30],
    [10,80,90],
    [30,50,80]
])
n2
n2.shape

(3, 3)

# Initialize Numpy array with zeros

In [189]:
n3=np.zeros((2,3))
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

# initialization a array of matrix with full then

In [190]:
n4=np.full((3,3),9)
n4

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

# initialization of NumPy array within a range

In [191]:
n5=np.arange(10,20)
n5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [192]:
n5=np.arange(10,19).reshape(3,3)
n5

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

# initialization of the NumPy array with the skip numbers

In [193]:
n6=np.arange(1,10,2)
n6

array([1, 3, 5, 7, 9])

# initialization NumPy array with the random numbers

In [194]:

n7=np.random.randint(100000,1000000,50)
n7

array([892618, 206232, 544176, 212796, 994027, 873148, 700381, 914617,
       978506, 914922, 216809, 670630, 802626, 875961, 857436, 363774,
       565503, 983907, 756972, 654417, 202279, 247011, 657347, 819089,
       740229, 389058, 460821, 280468, 161034, 845927, 552796, 257719,
       166655, 549532, 600864, 563671, 768081, 885234, 947395, 879706,
       485779, 382838, 482615, 982854, 265433, 185446, 596760, 330037,
       559329, 175014], dtype=int32)

# joining numpy arrays

In [195]:
a = np.arange(1,11)
b = np.arange(1,21,2)
c = np.random.randint(1,100,10)
d = np.random.randint(1,30,10)
e = np.random.randint(1,50,10)
print(a,b,c,d,e)
np.vstack((a,b,c,d,e))

[ 1  2  3  4  5  6  7  8  9 10] [ 1  3  5  7  9 11 13 15 17 19] [83 79 78 78 73 73 40 58  7 47] [27  9 18 15 26 12 12  1 10 23] [46 16 11 36 29 38  8 44 42 19]


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [83, 79, 78, 78, 73, 73, 40, 58,  7, 47],
       [27,  9, 18, 15, 26, 12, 12,  1, 10, 23],
       [46, 16, 11, 36, 29, 38,  8, 44, 42, 19]])

In [196]:
np.column_stack((a,b,c,d,e))

array([[ 1,  1, 83, 27, 46],
       [ 2,  3, 79,  9, 16],
       [ 3,  5, 78, 18, 11],
       [ 4,  7, 78, 15, 36],
       [ 5,  9, 73, 26, 29],
       [ 6, 11, 73, 12, 38],
       [ 7, 13, 40, 12,  8],
       [ 8, 15, 58,  1, 44],
       [ 9, 17,  7, 10, 42],
       [10, 19, 47, 23, 19]])

# Numpy intersection and differences

In [197]:
x=np.array([10,20,30,40,50,60])
y=np.array([30,50,90,40,70,60])
np.intersect1d(x,y)


array([30, 40, 50, 60])

In [198]:
np.setdiff1d(x,y)

array([10, 20])

# Addition of NumPy Arrays

In [199]:
t=np.array([10,20])
s=np.array([30,70])
np.sum([t,s])

np.int64(130)

In [200]:
np.sum([t,s],axis=0)


array([40, 90])

In [201]:
np.sum([t,s],axis=1)

array([ 30, 100])

# NumPy array mathematics

In [202]:
p=np.array([10,20,30])

In [203]:
p+1


array([11, 21, 31])

In [204]:
p-1


array([ 9, 19, 29])

In [205]:

p+p

array([20, 40, 60])

In [206]:
p*p

array([100, 400, 900])

In [207]:
p**4

array([ 10000, 160000, 810000])

In [208]:
p/p

array([1., 1., 1.])

# NumPy Math Functions

In [209]:
nn=np.array([10,20,30,60])

In [210]:
np.mean(nn)

np.float64(30.0)

In [211]:
np.median(nn)

np.float64(25.0)

In [212]:
np.std(nn)

np.float64(18.708286933869708)

In [213]:
np.quantile(nn,0.50)

np.float64(25.0)

In [214]:
np.var(nn)

np.float64(350.0)

In [215]:
np.cov(nn)

array(466.66666667)

In [216]:
np.max(nn)

np.int64(60)

# 

# Saving and Loading NumPy arrays

In [217]:
n11=np.array([10,20,30,40,50])

In [218]:
np.save('my_name',n11) #saving the numpy array

In [219]:
np.load('my_name.npy')

array([10, 20, 30, 40, 50])

# Identity Vs Eye

In [220]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [221]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [222]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# Einstein Summation Convetion Method

This function is used to compute many multi-dimnensional and linear algebric operations on arrays.

In [223]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(11,20).reshape(3,3)
a,b

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]))

In [224]:
## Extracts diagonals
np.einsum('ii->i',a)

array([1, 5, 9])

In [225]:
## Transpose
np.einsum('ij->ji',a)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [226]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [227]:
## Determinant
print(np.linalg.det(a))

0.0


In [228]:
np.linalg.inv(b)

array([[ 1.40737488e+14, -2.81474977e+14,  1.40737488e+14],
       [-2.81474977e+14,  5.62949953e+14, -2.81474977e+14],
       [ 1.40737488e+14, -2.81474977e+14,  1.40737488e+14]])

In [229]:
## Matrix Multiplication
np.einsum('ij,jk',a,b)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

# Matrix and Vector Multiplication

In [230]:
A = np.array([[1,2],[3,4],[5,6]])
x = np.array([7,8])
print(np.einsum('ij,j->i',A,x))

[23 53 83]
